name: Check the bins!

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual Run Tag'
        required: false
        type: boolean
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3    
    env:
      PYTHONUNBUFFERED: "1"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable # Use latest stable version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run the script!
      env:
        HOUSENO: ${{ secrets.HOUSENO }}
        POSTCODE: ${{ secrets.POSTCODE }}
      run: |
        # No need to modify PATH for chromedriver if setup-chrome handles it
        echo "Running script..."
        python bins.py -n "$HOUSENO" -p "$POSTCODE"
        echo "Script done."
    - name: Store json
      uses: actions/upload-artifact@v4
      with:
        name: bin json
        path: bins.json

    - name: Add to calendar!
      if: github.ref == 'refs/heads/main'
      env:
        CRED: ${{ secrets.CRED }}
        TOKEN: ${{ secrets.TOKEN }}
        CALID: ${{ secrets.CALID }}
      run: |
        pip install gcsa
        echo "$CRED" > credentials.json
        echo -n "$TOKEN" | python pickler.py
        echo "Created files, running script"
        python -u caltest.py -i $CALID -f bins.json
        echo "Script done."
