name: Check the bins!

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies (chrome, chromedriver, selenium)
      run: |
        #sudo apt update
        wget -q https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.57/linux64/chrome-linux64.zip
        unzip chrome-linux64.zip
        sudo mv chrome-linux64/chrome /usr/bin/chrome
        sudo chown root:root /usr/bin/chrome
        sudo chmod +x /usr/bin/chrome

        wget -q https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.57/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

        python -m pip install --upgrade pip
        pip install selenium gcsa
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run the script!
      env:
        HOUSENO: ${{ secrets.HOUSENO }}
        POSTCODE: ${{ secrets.POSTCODE }}
      run: |
        PATH=$(echo "$PATH" | sed -e 's/:\/usr\/bin\/google-chrome$//')
        echo "Running script..."
        python bins.py -n "$HOUSENO" -p "$POSTCODE"
        echo "Script done."
    - name: Store json
      uses: actions/upload-artifact@v4
      with:
        name: bin json
        path: bins.json

    - name: Add to calendar!
      env:
        CRED: ${{ secrets.CRED }}
        TOKEN: ${{ secrets.TOKEN }}
        CALID: ${{ secrets.CALID }}
      run: |
        echo "Create files"
        echo "$CRED" > credentials.json
        echo "$TOKEN" > token.json
        echo "Running script..."
        python caltest.py -i "$CALID"
        echo "Script done."
