name: Check the bins!

on:
  workflow_dispatch:
    inputs:
      tags:
      description: 'Manual Run Tag'
      required: false
      type: boolean
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3    
    env:
      PYTHONUNBUFFERED: "1"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies (chrome, chromedriver, selenium)
      run: |
        sudo apt-get update
        CHROME_VERSION=122.0.6261.57
        wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}-1_amd64.deb
        sudo apt install -y /tmp/chrome.deb

        #wget -q https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.57/linux64/chromedriver-linux64.zip
        wget -q https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

        python -m pip install --upgrade pip
        pip install selenium gcsa
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run the script!
      env:
        HOUSENO: ${{ secrets.HOUSENO }}
        POSTCODE: ${{ secrets.POSTCODE }}
      run: |
        PATH=$(echo "$PATH" | sed -e 's/:\/usr\/bin\/google-chrome$//')
        echo "Running script..."
        python bins.py -n "$HOUSENO" -p "$POSTCODE"
        echo "Script done."
    - name: Store json
      uses: actions/upload-artifact@v4
      with:
        name: bin json
        path: bins.json

    - name: Add to calendar!
      env:
        CRED: ${{ secrets.CRED }}
        TOKEN: ${{ secrets.TOKEN }}
        CALID: ${{ secrets.CALID }}
      run: |
        pip install gcsa
        echo "$CRED" > credentials.json
        echo -n "$TOKEN" | python pickler.py
        echo "Created files, running script"
        python -u caltest.py -i $CALID -f bins.json
        echo "Script done."
